### ISSUE TITLE
Instance requirements for MAS-Manage

### ISSUE THREAD

**Issue by tcskill** [cloud-native-toolkit/terraform-gitops-db2-schema#4]
@triceam found this for the db2 instance operator, this is what is needed https://www.ibm.com/docs/en/maximo-manage/8.3.0?topic=deployment-configuring-db2

**Comment by triceam** [comment]
clsing b/c this is not an issue for the db2-instance module.  this should be part of https://github.com/cloud-native-toolkit/software-everywhere/issues/8

**Comment by tcskill** [comment]
agreed moving the issue to mas-manage
